Update crib-cheat_git.md: Spelling of "Commiting" is changed into "Committing"
htw-pv3/literature pull request #156
Opened 2022-04-19 21:27 UTC by Dipesh563353

2022-04-19 21:59 UTC, Scorpey97 commented
we wanted to merge into the 'dev' branch first

2022-04-19 22:01 UTC, Scorpey97 commented
you can change it right in the head of the pull request

2022-04-20 09:24 UTC, Dipesh563353 commented
How can I merge into the 'dev' branch? @Scorpey97

2022-04-20 09:32 UTC, ELEMENTALengineering commented
Wenn du den Pull-Request erstellst, kannst du auswählen ob master oder dev ....

2022-04-20 09:32 UTC, JohannesBru commented
@Dipesh563353 at the top of this window right side click on "Edit" -> there you can edit your PR.  -> Right under the title of the PR you can change "base" from master to dev

2022-04-20 09:59 UTC, JohannesBru requested changes
This PR trys to merge into master. Change base branch from master to dev before merging!

2022-04-21 15:27 UTC, JohannesBru approved these changes
Looks Fine now. One small addition: the feature branch name does not follow the guidelines. A change would be nice but as this is the learning repo it's fine from my point of view.

Thanks for contributing!

2022-04-29 10:06 UTC, Ludee commented
Here is a Merge Conflict! Please do not touch, we will solve it together next time!

2025-05-14 19:47 UTC, closed without merging